//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwizzProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Responses", Namespace="http://tempuri.org/")]
    public partial class Responses : object
    {
        
        private bool HasResultsField;
        
        private object ResponseDataField;
        
        private string ResponseErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool HasResults
        {
            get
            {
                return this.HasResultsField;
            }
            set
            {
                this.HasResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object ResponseData
        {
            get
            {
                return this.ResponseDataField;
            }
            set
            {
                this.ResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SwizzProxy.SwizzProxySoap")]
    public interface SwizzProxySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnquireAccountBalanceAPP", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.EnquireAccountBalanceAPPResponse> EnquireAccountBalanceAPPAsync(SwizzProxy.EnquireAccountBalanceAPPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMemberInformationAPP", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.GetMemberInformationAPPResponse> GetMemberInformationAPPAsync(SwizzProxy.GetMemberInformationAPPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUrlHere", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.TestUrlHereResponse> TestUrlHereAsync(SwizzProxy.TestUrlHereRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MINISTATEMENTApp", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.MINISTATEMENTAppResponse> MINISTATEMENTAppAsync(SwizzProxy.MINISTATEMENTAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnquireLoanBalanceApp", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.EnquireLoanBalanceAppResponse> EnquireLoanBalanceAppAsync(SwizzProxy.EnquireLoanBalanceAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnquireLoanGuarantorsApp", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.EnquireLoanGuarantorsAppResponse> EnquireLoanGuarantorsAppAsync(SwizzProxy.EnquireLoanGuarantorsAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnquireLoansGuaranteedApp", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.EnquireLoansGuaranteedAppResponse> EnquireLoansGuaranteedAppAsync(SwizzProxy.EnquireLoansGuaranteedAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWSSAccountBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.GetWSSAccountBalanceResponse> GetWSSAccountBalanceAsync(SwizzProxy.GetWSSAccountBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSSAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.WSSAccountResponse> WSSAccountAsync(SwizzProxy.WSSAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoanAmountLimit", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.GetLoanAmountLimitResponse> GetLoanAmountLimitAsync(SwizzProxy.GetLoanAmountLimitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApplyLoan", ReplyAction="*")]
        System.Threading.Tasks.Task<SwizzProxy.ApplyLoanResponse> ApplyLoanAsync(SwizzProxy.ApplyLoanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireAccountBalanceAPPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireAccountBalanceAPP", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireAccountBalanceAPPRequestBody Body;
        
        public EnquireAccountBalanceAPPRequest()
        {
        }
        
        public EnquireAccountBalanceAPPRequest(SwizzProxy.EnquireAccountBalanceAPPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireAccountBalanceAPPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accountno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime transactiondate;
        
        public EnquireAccountBalanceAPPRequestBody()
        {
        }
        
        public EnquireAccountBalanceAPPRequestBody(string traceid, string phonenumber, string documentno, string accountno, System.DateTime transactiondate)
        {
            this.traceid = traceid;
            this.phonenumber = phonenumber;
            this.documentno = documentno;
            this.accountno = accountno;
            this.transactiondate = transactiondate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireAccountBalanceAPPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireAccountBalanceAPPResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireAccountBalanceAPPResponseBody Body;
        
        public EnquireAccountBalanceAPPResponse()
        {
        }
        
        public EnquireAccountBalanceAPPResponse(SwizzProxy.EnquireAccountBalanceAPPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireAccountBalanceAPPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses EnquireAccountBalanceAPPResult;
        
        public EnquireAccountBalanceAPPResponseBody()
        {
        }
        
        public EnquireAccountBalanceAPPResponseBody(SwizzProxy.Responses EnquireAccountBalanceAPPResult)
        {
            this.EnquireAccountBalanceAPPResult = EnquireAccountBalanceAPPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberInformationAPPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberInformationAPP", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.GetMemberInformationAPPRequestBody Body;
        
        public GetMemberInformationAPPRequest()
        {
        }
        
        public GetMemberInformationAPPRequest(SwizzProxy.GetMemberInformationAPPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberInformationAPPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneNumber;
        
        public GetMemberInformationAPPRequestBody()
        {
        }
        
        public GetMemberInformationAPPRequestBody(string phoneNumber)
        {
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberInformationAPPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberInformationAPPResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.GetMemberInformationAPPResponseBody Body;
        
        public GetMemberInformationAPPResponse()
        {
        }
        
        public GetMemberInformationAPPResponse(SwizzProxy.GetMemberInformationAPPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberInformationAPPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses GetMemberInformationAPPResult;
        
        public GetMemberInformationAPPResponseBody()
        {
        }
        
        public GetMemberInformationAPPResponseBody(SwizzProxy.Responses GetMemberInformationAPPResult)
        {
            this.GetMemberInformationAPPResult = GetMemberInformationAPPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUrlHereRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUrlHere", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.TestUrlHereRequestBody Body;
        
        public TestUrlHereRequest()
        {
        }
        
        public TestUrlHereRequest(SwizzProxy.TestUrlHereRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUrlHereRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accountno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime transactiondate;
        
        public TestUrlHereRequestBody()
        {
        }
        
        public TestUrlHereRequestBody(string traceid, string phonenumber, string documentno, string accountno, System.DateTime transactiondate)
        {
            this.traceid = traceid;
            this.phonenumber = phonenumber;
            this.documentno = documentno;
            this.accountno = accountno;
            this.transactiondate = transactiondate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUrlHereResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUrlHereResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.TestUrlHereResponseBody Body;
        
        public TestUrlHereResponse()
        {
        }
        
        public TestUrlHereResponse(SwizzProxy.TestUrlHereResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUrlHereResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestUrlHereResult;
        
        public TestUrlHereResponseBody()
        {
        }
        
        public TestUrlHereResponseBody(string TestUrlHereResult)
        {
            this.TestUrlHereResult = TestUrlHereResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MINISTATEMENTAppRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MINISTATEMENTApp", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.MINISTATEMENTAppRequestBody Body;
        
        public MINISTATEMENTAppRequest()
        {
        }
        
        public MINISTATEMENTAppRequest(SwizzProxy.MINISTATEMENTAppRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MINISTATEMENTAppRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime transactionDate;
        
        public MINISTATEMENTAppRequestBody()
        {
        }
        
        public MINISTATEMENTAppRequestBody(string traceid, string phonenumber, string documentNo, string accountNumber, System.DateTime transactionDate)
        {
            this.traceid = traceid;
            this.phonenumber = phonenumber;
            this.documentNo = documentNo;
            this.accountNumber = accountNumber;
            this.transactionDate = transactionDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MINISTATEMENTAppResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MINISTATEMENTAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.MINISTATEMENTAppResponseBody Body;
        
        public MINISTATEMENTAppResponse()
        {
        }
        
        public MINISTATEMENTAppResponse(SwizzProxy.MINISTATEMENTAppResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MINISTATEMENTAppResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses MINISTATEMENTAppResult;
        
        public MINISTATEMENTAppResponseBody()
        {
        }
        
        public MINISTATEMENTAppResponseBody(SwizzProxy.Responses MINISTATEMENTAppResult)
        {
            this.MINISTATEMENTAppResult = MINISTATEMENTAppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireLoanBalanceAppRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireLoanBalanceApp", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireLoanBalanceAppRequestBody Body;
        
        public EnquireLoanBalanceAppRequest()
        {
        }
        
        public EnquireLoanBalanceAppRequest(SwizzProxy.EnquireLoanBalanceAppRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireLoanBalanceAppRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string documentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime transactionDate;
        
        public EnquireLoanBalanceAppRequestBody()
        {
        }
        
        public EnquireLoanBalanceAppRequestBody(string traceid, string phonenumber, string documentNumber, System.DateTime transactionDate)
        {
            this.traceid = traceid;
            this.phonenumber = phonenumber;
            this.documentNumber = documentNumber;
            this.transactionDate = transactionDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireLoanBalanceAppResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireLoanBalanceAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireLoanBalanceAppResponseBody Body;
        
        public EnquireLoanBalanceAppResponse()
        {
        }
        
        public EnquireLoanBalanceAppResponse(SwizzProxy.EnquireLoanBalanceAppResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireLoanBalanceAppResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses EnquireLoanBalanceAppResult;
        
        public EnquireLoanBalanceAppResponseBody()
        {
        }
        
        public EnquireLoanBalanceAppResponseBody(SwizzProxy.Responses EnquireLoanBalanceAppResult)
        {
            this.EnquireLoanBalanceAppResult = EnquireLoanBalanceAppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireLoanGuarantorsAppRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireLoanGuarantorsApp", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireLoanGuarantorsAppRequestBody Body;
        
        public EnquireLoanGuarantorsAppRequest()
        {
        }
        
        public EnquireLoanGuarantorsAppRequest(SwizzProxy.EnquireLoanGuarantorsAppRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireLoanGuarantorsAppRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime transactiondate;
        
        public EnquireLoanGuarantorsAppRequestBody()
        {
        }
        
        public EnquireLoanGuarantorsAppRequestBody(string traceid, string documentno, string phonenumber, System.DateTime transactiondate)
        {
            this.traceid = traceid;
            this.documentno = documentno;
            this.phonenumber = phonenumber;
            this.transactiondate = transactiondate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireLoanGuarantorsAppResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireLoanGuarantorsAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireLoanGuarantorsAppResponseBody Body;
        
        public EnquireLoanGuarantorsAppResponse()
        {
        }
        
        public EnquireLoanGuarantorsAppResponse(SwizzProxy.EnquireLoanGuarantorsAppResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireLoanGuarantorsAppResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses EnquireLoanGuarantorsAppResult;
        
        public EnquireLoanGuarantorsAppResponseBody()
        {
        }
        
        public EnquireLoanGuarantorsAppResponseBody(SwizzProxy.Responses EnquireLoanGuarantorsAppResult)
        {
            this.EnquireLoanGuarantorsAppResult = EnquireLoanGuarantorsAppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireLoansGuaranteedAppRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireLoansGuaranteedApp", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireLoansGuaranteedAppRequestBody Body;
        
        public EnquireLoansGuaranteedAppRequest()
        {
        }
        
        public EnquireLoansGuaranteedAppRequest(SwizzProxy.EnquireLoansGuaranteedAppRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireLoansGuaranteedAppRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime transactindate;
        
        public EnquireLoansGuaranteedAppRequestBody()
        {
        }
        
        public EnquireLoansGuaranteedAppRequestBody(string traceid, string documentno, string phonenumber, System.DateTime transactindate)
        {
            this.traceid = traceid;
            this.documentno = documentno;
            this.phonenumber = phonenumber;
            this.transactindate = transactindate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnquireLoansGuaranteedAppResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnquireLoansGuaranteedAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.EnquireLoansGuaranteedAppResponseBody Body;
        
        public EnquireLoansGuaranteedAppResponse()
        {
        }
        
        public EnquireLoansGuaranteedAppResponse(SwizzProxy.EnquireLoansGuaranteedAppResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnquireLoansGuaranteedAppResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses EnquireLoansGuaranteedAppResult;
        
        public EnquireLoansGuaranteedAppResponseBody()
        {
        }
        
        public EnquireLoansGuaranteedAppResponseBody(SwizzProxy.Responses EnquireLoansGuaranteedAppResult)
        {
            this.EnquireLoansGuaranteedAppResult = EnquireLoansGuaranteedAppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWSSAccountBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWSSAccountBalance", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.GetWSSAccountBalanceRequestBody Body;
        
        public GetWSSAccountBalanceRequest()
        {
        }
        
        public GetWSSAccountBalanceRequest(SwizzProxy.GetWSSAccountBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWSSAccountBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phonenumber;
        
        public GetWSSAccountBalanceRequestBody()
        {
        }
        
        public GetWSSAccountBalanceRequestBody(string phonenumber)
        {
            this.phonenumber = phonenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWSSAccountBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWSSAccountBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.GetWSSAccountBalanceResponseBody Body;
        
        public GetWSSAccountBalanceResponse()
        {
        }
        
        public GetWSSAccountBalanceResponse(SwizzProxy.GetWSSAccountBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWSSAccountBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses GetWSSAccountBalanceResult;
        
        public GetWSSAccountBalanceResponseBody()
        {
        }
        
        public GetWSSAccountBalanceResponseBody(SwizzProxy.Responses GetWSSAccountBalanceResult)
        {
            this.GetWSSAccountBalanceResult = GetWSSAccountBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSSAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSSAccount", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.WSSAccountRequestBody Body;
        
        public WSSAccountRequest()
        {
        }
        
        public WSSAccountRequest(SwizzProxy.WSSAccountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSSAccountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phonenumber;
        
        public WSSAccountRequestBody()
        {
        }
        
        public WSSAccountRequestBody(string phonenumber)
        {
            this.phonenumber = phonenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSSAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSSAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.WSSAccountResponseBody Body;
        
        public WSSAccountResponse()
        {
        }
        
        public WSSAccountResponse(SwizzProxy.WSSAccountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSSAccountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses WSSAccountResult;
        
        public WSSAccountResponseBody()
        {
        }
        
        public WSSAccountResponseBody(SwizzProxy.Responses WSSAccountResult)
        {
            this.WSSAccountResult = WSSAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoanAmountLimitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoanAmountLimit", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.GetLoanAmountLimitRequestBody Body;
        
        public GetLoanAmountLimitRequest()
        {
        }
        
        public GetLoanAmountLimitRequest(SwizzProxy.GetLoanAmountLimitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoanAmountLimitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loancode;
        
        public GetLoanAmountLimitRequestBody()
        {
        }
        
        public GetLoanAmountLimitRequestBody(string phonenumber, string loancode)
        {
            this.phonenumber = phonenumber;
            this.loancode = loancode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoanAmountLimitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoanAmountLimitResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.GetLoanAmountLimitResponseBody Body;
        
        public GetLoanAmountLimitResponse()
        {
        }
        
        public GetLoanAmountLimitResponse(SwizzProxy.GetLoanAmountLimitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoanAmountLimitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses GetLoanAmountLimitResult;
        
        public GetLoanAmountLimitResponseBody()
        {
        }
        
        public GetLoanAmountLimitResponseBody(SwizzProxy.Responses GetLoanAmountLimitResult)
        {
            this.GetLoanAmountLimitResult = GetLoanAmountLimitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyLoanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyLoan", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.ApplyLoanRequestBody Body;
        
        public ApplyLoanRequest()
        {
        }
        
        public ApplyLoanRequest(SwizzProxy.ApplyLoanRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplyLoanRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accountno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string loancode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal amountapplied;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal repaymentperiod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime transactiondate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string narration;
        
        public ApplyLoanRequestBody()
        {
        }
        
        public ApplyLoanRequestBody(string traceid, string documentno, string phonenumber, string accountno, string loancode, decimal amountapplied, decimal repaymentperiod, System.DateTime transactiondate, string narration)
        {
            this.traceid = traceid;
            this.documentno = documentno;
            this.phonenumber = phonenumber;
            this.accountno = accountno;
            this.loancode = loancode;
            this.amountapplied = amountapplied;
            this.repaymentperiod = repaymentperiod;
            this.transactiondate = transactiondate;
            this.narration = narration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyLoanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyLoanResponse", Namespace="http://tempuri.org/", Order=0)]
        public SwizzProxy.ApplyLoanResponseBody Body;
        
        public ApplyLoanResponse()
        {
        }
        
        public ApplyLoanResponse(SwizzProxy.ApplyLoanResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplyLoanResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SwizzProxy.Responses ApplyLoanResult;
        
        public ApplyLoanResponseBody()
        {
        }
        
        public ApplyLoanResponseBody(SwizzProxy.Responses ApplyLoanResult)
        {
            this.ApplyLoanResult = ApplyLoanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SwizzProxySoapChannel : SwizzProxy.SwizzProxySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SwizzProxySoapClient : System.ServiceModel.ClientBase<SwizzProxy.SwizzProxySoap>, SwizzProxy.SwizzProxySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SwizzProxySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SwizzProxySoapClient.GetBindingForEndpoint(endpointConfiguration), SwizzProxySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SwizzProxySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SwizzProxySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SwizzProxySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SwizzProxySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SwizzProxySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.EnquireAccountBalanceAPPResponse> SwizzProxy.SwizzProxySoap.EnquireAccountBalanceAPPAsync(SwizzProxy.EnquireAccountBalanceAPPRequest request)
        {
            return base.Channel.EnquireAccountBalanceAPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.EnquireAccountBalanceAPPResponse> EnquireAccountBalanceAPPAsync(string traceid, string phonenumber, string documentno, string accountno, System.DateTime transactiondate)
        {
            SwizzProxy.EnquireAccountBalanceAPPRequest inValue = new SwizzProxy.EnquireAccountBalanceAPPRequest();
            inValue.Body = new SwizzProxy.EnquireAccountBalanceAPPRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.documentno = documentno;
            inValue.Body.accountno = accountno;
            inValue.Body.transactiondate = transactiondate;
            return ((SwizzProxy.SwizzProxySoap)(this)).EnquireAccountBalanceAPPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.GetMemberInformationAPPResponse> SwizzProxy.SwizzProxySoap.GetMemberInformationAPPAsync(SwizzProxy.GetMemberInformationAPPRequest request)
        {
            return base.Channel.GetMemberInformationAPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.GetMemberInformationAPPResponse> GetMemberInformationAPPAsync(string phoneNumber)
        {
            SwizzProxy.GetMemberInformationAPPRequest inValue = new SwizzProxy.GetMemberInformationAPPRequest();
            inValue.Body = new SwizzProxy.GetMemberInformationAPPRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            return ((SwizzProxy.SwizzProxySoap)(this)).GetMemberInformationAPPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.TestUrlHereResponse> SwizzProxy.SwizzProxySoap.TestUrlHereAsync(SwizzProxy.TestUrlHereRequest request)
        {
            return base.Channel.TestUrlHereAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.TestUrlHereResponse> TestUrlHereAsync(string traceid, string phonenumber, string documentno, string accountno, System.DateTime transactiondate)
        {
            SwizzProxy.TestUrlHereRequest inValue = new SwizzProxy.TestUrlHereRequest();
            inValue.Body = new SwizzProxy.TestUrlHereRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.documentno = documentno;
            inValue.Body.accountno = accountno;
            inValue.Body.transactiondate = transactiondate;
            return ((SwizzProxy.SwizzProxySoap)(this)).TestUrlHereAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.MINISTATEMENTAppResponse> SwizzProxy.SwizzProxySoap.MINISTATEMENTAppAsync(SwizzProxy.MINISTATEMENTAppRequest request)
        {
            return base.Channel.MINISTATEMENTAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.MINISTATEMENTAppResponse> MINISTATEMENTAppAsync(string traceid, string phonenumber, string documentNo, string accountNumber, System.DateTime transactionDate)
        {
            SwizzProxy.MINISTATEMENTAppRequest inValue = new SwizzProxy.MINISTATEMENTAppRequest();
            inValue.Body = new SwizzProxy.MINISTATEMENTAppRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.documentNo = documentNo;
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.transactionDate = transactionDate;
            return ((SwizzProxy.SwizzProxySoap)(this)).MINISTATEMENTAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.EnquireLoanBalanceAppResponse> SwizzProxy.SwizzProxySoap.EnquireLoanBalanceAppAsync(SwizzProxy.EnquireLoanBalanceAppRequest request)
        {
            return base.Channel.EnquireLoanBalanceAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.EnquireLoanBalanceAppResponse> EnquireLoanBalanceAppAsync(string traceid, string phonenumber, string documentNumber, System.DateTime transactionDate)
        {
            SwizzProxy.EnquireLoanBalanceAppRequest inValue = new SwizzProxy.EnquireLoanBalanceAppRequest();
            inValue.Body = new SwizzProxy.EnquireLoanBalanceAppRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.documentNumber = documentNumber;
            inValue.Body.transactionDate = transactionDate;
            return ((SwizzProxy.SwizzProxySoap)(this)).EnquireLoanBalanceAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.EnquireLoanGuarantorsAppResponse> SwizzProxy.SwizzProxySoap.EnquireLoanGuarantorsAppAsync(SwizzProxy.EnquireLoanGuarantorsAppRequest request)
        {
            return base.Channel.EnquireLoanGuarantorsAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.EnquireLoanGuarantorsAppResponse> EnquireLoanGuarantorsAppAsync(string traceid, string documentno, string phonenumber, System.DateTime transactiondate)
        {
            SwizzProxy.EnquireLoanGuarantorsAppRequest inValue = new SwizzProxy.EnquireLoanGuarantorsAppRequest();
            inValue.Body = new SwizzProxy.EnquireLoanGuarantorsAppRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.documentno = documentno;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.transactiondate = transactiondate;
            return ((SwizzProxy.SwizzProxySoap)(this)).EnquireLoanGuarantorsAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.EnquireLoansGuaranteedAppResponse> SwizzProxy.SwizzProxySoap.EnquireLoansGuaranteedAppAsync(SwizzProxy.EnquireLoansGuaranteedAppRequest request)
        {
            return base.Channel.EnquireLoansGuaranteedAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.EnquireLoansGuaranteedAppResponse> EnquireLoansGuaranteedAppAsync(string traceid, string documentno, string phonenumber, System.DateTime transactindate)
        {
            SwizzProxy.EnquireLoansGuaranteedAppRequest inValue = new SwizzProxy.EnquireLoansGuaranteedAppRequest();
            inValue.Body = new SwizzProxy.EnquireLoansGuaranteedAppRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.documentno = documentno;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.transactindate = transactindate;
            return ((SwizzProxy.SwizzProxySoap)(this)).EnquireLoansGuaranteedAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.GetWSSAccountBalanceResponse> SwizzProxy.SwizzProxySoap.GetWSSAccountBalanceAsync(SwizzProxy.GetWSSAccountBalanceRequest request)
        {
            return base.Channel.GetWSSAccountBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.GetWSSAccountBalanceResponse> GetWSSAccountBalanceAsync(string phonenumber)
        {
            SwizzProxy.GetWSSAccountBalanceRequest inValue = new SwizzProxy.GetWSSAccountBalanceRequest();
            inValue.Body = new SwizzProxy.GetWSSAccountBalanceRequestBody();
            inValue.Body.phonenumber = phonenumber;
            return ((SwizzProxy.SwizzProxySoap)(this)).GetWSSAccountBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.WSSAccountResponse> SwizzProxy.SwizzProxySoap.WSSAccountAsync(SwizzProxy.WSSAccountRequest request)
        {
            return base.Channel.WSSAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.WSSAccountResponse> WSSAccountAsync(string phonenumber)
        {
            SwizzProxy.WSSAccountRequest inValue = new SwizzProxy.WSSAccountRequest();
            inValue.Body = new SwizzProxy.WSSAccountRequestBody();
            inValue.Body.phonenumber = phonenumber;
            return ((SwizzProxy.SwizzProxySoap)(this)).WSSAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.GetLoanAmountLimitResponse> SwizzProxy.SwizzProxySoap.GetLoanAmountLimitAsync(SwizzProxy.GetLoanAmountLimitRequest request)
        {
            return base.Channel.GetLoanAmountLimitAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.GetLoanAmountLimitResponse> GetLoanAmountLimitAsync(string phonenumber, string loancode)
        {
            SwizzProxy.GetLoanAmountLimitRequest inValue = new SwizzProxy.GetLoanAmountLimitRequest();
            inValue.Body = new SwizzProxy.GetLoanAmountLimitRequestBody();
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.loancode = loancode;
            return ((SwizzProxy.SwizzProxySoap)(this)).GetLoanAmountLimitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SwizzProxy.ApplyLoanResponse> SwizzProxy.SwizzProxySoap.ApplyLoanAsync(SwizzProxy.ApplyLoanRequest request)
        {
            return base.Channel.ApplyLoanAsync(request);
        }
        
        public System.Threading.Tasks.Task<SwizzProxy.ApplyLoanResponse> ApplyLoanAsync(string traceid, string documentno, string phonenumber, string accountno, string loancode, decimal amountapplied, decimal repaymentperiod, System.DateTime transactiondate, string narration)
        {
            SwizzProxy.ApplyLoanRequest inValue = new SwizzProxy.ApplyLoanRequest();
            inValue.Body = new SwizzProxy.ApplyLoanRequestBody();
            inValue.Body.traceid = traceid;
            inValue.Body.documentno = documentno;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.accountno = accountno;
            inValue.Body.loancode = loancode;
            inValue.Body.amountapplied = amountapplied;
            inValue.Body.repaymentperiod = repaymentperiod;
            inValue.Body.transactiondate = transactiondate;
            inValue.Body.narration = narration;
            return ((SwizzProxy.SwizzProxySoap)(this)).ApplyLoanAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SwizzProxySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SwizzProxySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SwizzProxySoap))
            {
                return new System.ServiceModel.EndpointAddress("http://197.232.170.121:8080/swizz/SwizzProxy.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SwizzProxySoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://197.232.170.121:8080/swizz/SwizzProxy.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SwizzProxySoap,
            
            SwizzProxySoap12,
        }
    }
}
